### ISSUE TITLE
Band energy metric throws ValueError

### ISSUE THREAD

**Issue by nerkulec** [mala-project/mala#427]
When using
```python
parameters.running.after_before_training_metric = "band_energy"
```
together with
```python
parameters.data.output_rescaling_type = "feature-wise-normal"
```
Band energy metric (before training) throws ValueError
Error traceback:
```
Traceback (most recent call last):
  File "train_error.py", line 47, in <module>
    test_trainer.train_network()
  File "/home/brzoza73/casus/mala/mala/network/trainer.py", line 179, in train_network
    vloss = self.__validate_network(self.network,
  File "/home/brzoza73/casus/mala/mala/network/trainer.py", line 780, in __validate_network
    fe_actual = calculator.\
  File "/home/brzoza73/casus/mala/mala/targets/ldos.py", line 916, in get_self_consistent_fermi_energy
    return dos_calculator. \
  File "/home/brzoza73/casus/mala/mala/targets/dos.py", line 788, in get_self_consistent_fermi_energy
    fermi_energy_sc = toms748(lambda fermi_sc:
  File "/trinity/shared/pkg/devel/python/3.8.0/lib/python3.8/site-packages/scipy/optimize/zeros.py", line 1372, in toms748
    result = solver.solve(f, a, b, args=args, k=k, xtol=xtol, rtol=rtol,
  File "/trinity/shared/pkg/devel/python/3.8.0/lib/python3.8/site-packages/scipy/optimize/zeros.py", line 1219, in solve
    status, xn = self.start(f, a, b, args)
  File "/trinity/shared/pkg/devel/python/3.8.0/lib/python3.8/site-packages/scipy/optimize/zeros.py", line 1107, in start
    fa = self._callf(a)
  File "/trinity/shared/pkg/devel/python/3.8.0/lib/python3.8/site-packages/scipy/optimize/zeros.py", line 1084, in _callf
    raise ValueError("Invalid function value: f(%f) -> %s " % (x, fx))
ValueError: Invalid function value: f(-13.500000) -> nan
```
Code to reproduce (run on hemera):
```python
import os

import mala

parameters = mala.Parameters()
parameters.data.data_splitting_type = "by_snapshot"
parameters.data.input_rescaling_type = "feature-wise-standard"
parameters.data.output_rescaling_type = "feature-wise-normal"

parameters.targets.target_type = "LDOS"
parameters.targets.ldos_gridsize = 201
parameters.targets.ldos_gridoffset_ev = -13.5
parameters.targets.ldos_gridspacing_ev = 0.1
parameters.running.max_number_epochs = 100
parameters.running.mini_batch_size = 40
parameters.running.learning_rate = 0.00001
parameters.running.trainingtype = "Adam"
parameters.running.after_before_training_metric = "band_energy"
parameters.verbosity = 1

snap_path   = "/bigdata/casus/wdm/Bartek_H2/H128/bispectrum/"
ldos_path   = "/bigdata/casus/wdm/Bartek_H2/H128/ldos/"
output_path = "/bigdata/casus/wdm/Bartek_H2/H128/outputs/"

data_handler = mala.DataHandler(parameters)
data_handler.add_snapshot(
  f"H_snapshot0.in.npy", snap_path,
  f"H_snapshot0.out.npy", ldos_path, "va",
  calculation_output_file=os.path.join(output_path, f"snapshot0.out"), 
)

data_handler.add_snapshot(
  f"H_snapshot1.in.npy", snap_path,
  f"H_snapshot1.out.npy", ldos_path, "tr",
  calculation_output_file=os.path.join(output_path, f"snapshot1.out")
)
data_handler.prepare_data()

parameters.network.layer_sizes = [
  data_handler.input_dimension,
  100,
  data_handler.output_dimension
]
parameters.network.layer_activations = ["ReLU"]
test_network = mala.Network(parameters)
test_trainer = mala.Trainer(parameters, test_network, data_handler)
test_trainer.train_network()
```

Note:
Doesn't happen for Be2 test data so this is data-dependent error.

Expected behavior:
Metric should return a bad value for randomly initialized model instead of throwing an error

**Comment by RandomDefaultUser** [comment]
I could reproduce the error and fixed it with #428. If the problem persists for some reason, let me know.
